FROM ruby:2.4
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /one-bit-flix
WORKDIR /one-bit-flix
COPY Gemfile /one-bit-flix/Gemfile
COPY Gemfile.lock /one-bit-flix/Gemfile.lock
RUN bundle install
COPY . /one-bit-flix
